import { Piazzolla } from "next/font/google"
import "./globals.css";

const spectral = Piazzolla({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800'],
  display: "swap",
  variable: "--font-pizzolla"
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className={spectral.className} lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
